language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: dh4oofNSRp5GEIXLf2PyxP8+vmEg/zEv94RaoLZOIXgGgdCHseN1QnX7i3gF7ZNNHotM+Ff9F6bE/wfCK/i+YwiW5aqZJJLNgoYqudQZY7HTbui4XM2oVTZy9UpCaf4gxQQPr3woL0OH1Ty1mw0F4cOjqv6V7UIjbrKhANhv601X0+KJsJMMvHVSJwrq0ga9JruocoTXCy+ogcR4MdJQMr1RK/mSYop4jPZ9d/EeUGgig4JHUqCATU53uxaK/su2z5AYWXTM6GQGxCigGOHmJLj5ISy88mFtA0+kQUeRVqVLEAoLPxX9z6onokjIJ+SFQIzsAAzMywoWDzlS9kIso4S8WE8hzK3ZaLmp1tIgT41t0DbNIl/7k+7No8blgs5GY1v14IcWLXVJIS5Y+pacNHfZdXfJgjwXk2aCugWhpwrlCYdJ2kIdbgOCdWZPeUCiCKlT1EMhM3C+tPr1se3uZp7Qyn80DAbHApjdgGWgrCtjzSvvy/25KAsqM9wK6xVKReefE4WcarAQ9xiCBeUXR+8N5cAhjKphY/YAOb4371ZOZ1d1Yz68Jw+hBHcfCaJKUvbsEtt4afn9Ba0HaMOGIDooB4rzc7Au2OI8eI2q3pVE/Fj3k/VyxLgS06nUOWmq2LQpbpoZiizQRHb5io1i4xPovlP5Km/7T1PFOeqw1lU=
  app: https://packtracker-app.herokuapp.com/
  on:
    repo: laursnow/PackTracker-Server
